### ISSUE TITLE
Login error cancel

### ISSUE THREAD

**Issue by sharplegacy** [den0un/CsgoReportBot#6]
If a Login to a steam Account fails for some reason, like "This account is currently deactivated and logins are disabled." the scripts stops working, could you please add to just try next Account than, or better also removes the non working Account from accounts.txt

**Comment by den0un** [comment]
@sharplegacy i did make some changes to the code.
i replaced the "break" with a "pass" so next time when the login fails it skips the account.
your idea about checking the accounts it great but in my case my report bot cant use a lot of accounts because steam blocks the ip temporarily, some people couldn't use more than 25 without getting an error message, i tried to fix it with proxies but i gave up xd...
putting a checking function is good but in our case we dont have a large list of accounts, so writing a function to test them isn't worth it
